### ISSUE TITLE
fix markdown within README.md file

### ISSUE THREAD

**Issue by goobric** [goobric/goobric#1]
please explain to me, what I have done incorrectly with the markdown code within the README.md file for the page to be displayed like this: (thank you so much)
![220321_1stIssue_readme](https://user-images.githubusercontent.com/23141638/159304990-e112e9e1-e1f3-40a5-b207-5b57c72e192f.png)

**Comment by eddiejaoude** [comment]
It looks ok in the `README.md` now, did you fix it?

**Comment by goobric** [comment]
this fixes #1
